POST http://localhost:3000/login
content-type: application/json

{
        "username": "HiALL",
        "password": "qwerty"
}

###
POST http://localhost:3000/forgotPassword
content-type: application/json

{
        "email":"hiall@hi.com"
}



###
POST http://localhost:3000/register
content-type: application/json

{
        "username": "HiALL",
        "password": "Hi",
        "email": "hiall@hi.com"
}

###
POST http://localhost:3000/protected
content-type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiSGlBTEwiLCJpYXQiOjE2NjY5ODA2MzQsImV4cCI6MTY2Njk4MDY3OX0.RFT31ymvcddy2QN2l3LkFR1DRmm0qfuVF_Rr8a9BlqI

###

POST http://localhost:3000/renewAccessToken
content-type: application/json

{   
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzcGFyZG8iLCJwYXNzd29yZCI6InFxdyIsImlhdCI6MTY2NjQ1NjgyMiwiZXhwIjoxNjY2NTQzMjIyfQ.i1K5Dca1ZRqLpwwNfBAuh-mD1jqmEIiEs_EINzGnQ48"
}


###
GET http://localhost:3000/login